# File Managed by Puppet
production:
<% if scope.lookupvar('puppetdashboard::db_host') -%>
  host: <%= scope.lookupvar('puppetdashboard::db_host') %>
<% end -%>
<% if scope.lookupvar('puppetdashboard::db_port') -%>
  port: <%= scope.lookupvar('puppetdashboard::db_port') %>
<% end -%>
  database: <%= scope.lookupvar('puppetdashboard::db_name') %>
  username: <%= scope.lookupvar('puppetdashboard::db_user') %>
  password: <%= scope.lookupvar('puppetdashboard::db_password') %>
  encoding: utf8
  adapter: mysql

development:
  database: dashboard_development
  username: dashboard
  password:
  encoding: utf8
  adapter: mysql

test:
  database: dashboard_test
  username: dashboard
  password:
  encoding: utf8
  adapter: mysql

